name: FAQ Automation

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  process-faq-proposal:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.issue.labels.*.name, 'faq-proposal')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv pip install --system -e .

      - name: Fetch issue body
        id: fetch_issue
        uses: actions/github-script@v7
        with:
          script: |
            // Get issue number from event or manual input
            const issueNumber = context.payload.issue?.number || ${{ inputs.issue_number || 'null' }};

            // Fetch issue if manually triggered
            const issue = context.payload.issue || await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            }).then(res => res.data);

            const body = issue.body || '';

            // Save issue body to file for Python to parse
            const fs = require('fs');
            fs.writeFileSync('/tmp/issue_body.txt', body);

            console.log('Fetched issue body, saved to /tmp/issue_body.txt');

      - name: Extract issue fields with Python
        id: extract
        run: |
          python scripts/extract_issue_fields.py < /tmp/issue_body.txt

      - name: Process FAQ with AI
        id: process
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Create simplified issue body for CLI (only needs question and answer)
          cat > /tmp/cli_issue_body.txt << 'EOF'
          ### Question
          ${{ steps.extract.outputs.question }}

          ### Answer
          ${{ steps.extract.outputs.answer }}
          EOF

          # Run FAQ automation CLI
          python -m faq_automation.cli \
            --issue-body "$(cat /tmp/cli_issue_body.txt)" \
            --issue-number ${{ github.event.issue.number || inputs.issue_number }} \
            --course "${{ steps.extract.outputs.course }}" \
            --model "gpt-5-nano" \
            --output-dir /tmp

          # Write decision output to GitHub Actions
          python scripts/write_faq_decision_output.py

      - name: Handle NEW or UPDATE action
        if: fromJson(steps.process.outputs.decision).action != 'DUPLICATE'
        uses: actions/github-script@v7
        with:
          script: |
            const decision = ${{ steps.process.outputs.decision }};
            const action = decision.action;
            const issueNumber = decision.issue_number;
            const prBody = decision.pr_body;
            const filePath = decision.file_path;

            // Create branch name
            const branchName = `faq-bot/issue-${issueNumber}`;

            // Configure git
            await exec.exec('git', ['config', 'user.name', 'FAQ Bot']);
            await exec.exec('git', ['config', 'user.email', 'faq-bot@datatalks.club']);

            // Fetch and checkout main, then create new branch from it
            await exec.exec('git', ['fetch', 'origin', 'main']);
            await exec.exec('git', ['checkout', 'main']);
            await exec.exec('git', ['checkout', '-b', branchName]);

            // Add modified files
            await exec.exec('git', ['add', filePath]);

            // Commit changes
            const commitMsg = `${action}: ${decision.decision.question.substring(0, 72)}`;
            await exec.exec('git', ['commit', '-m', commitMsg]);

            // Push branch
            await exec.exec('git', ['push', 'origin', branchName]);

            // Create pull request
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[FAQ Bot] ${action}: ${decision.decision.question.substring(0, 72)}`,
              head: branchName,
              base: 'main',
              body: prBody
            });

            // Comment on issue with PR link
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `✅ FAQ ${action} proposal created in PR #${pr.number}\n\nPlease review and approve the changes.`
            });

      - name: Handle DUPLICATE action
        if: fromJson(steps.process.outputs.decision).action == 'DUPLICATE'
        uses: actions/github-script@v7
        with:
          script: |
            const decision = ${{ steps.process.outputs.decision }};
            const comment = decision.comment;
            const issueNumber = decision.issue_number;

            // Post comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: comment
            });

            // Close issue
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: 'closed',
              state_reason: 'completed'
            });

      - name: Handle errors
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.payload.issue?.number || ${{ inputs.issue_number || 'null' }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `❌ FAQ Bot encountered an error processing this proposal.\n\nPlease check the [workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId}) for details.\n\nA maintainer will review this manually.`
            });
